### ISSUE TITLE
Is there any way to create a nifti file?

### ISSUE THREAD

**Issue by ziqianwang9** [dorianps/LESYMAP#10]
Hello developers,
thank you for providing this wonderful program.
And I want to use it on tumor patients.
As a very beginner, I don't know if this program just supply image result or there is any way that I could get a '.nii' format file to overlay it on T1 image?
Looking forward to your reply.
Thanks again.

Best regards,
Ziqian Wang

**Comment by ziqianwang9** [comment]
Hello developers,
thank you for providing this wonderful program.
And I want to use it on tumor patients. 
As a very beginner, I don't know if this program just supply image result or there is any way that I could get a '.nii' format file to overlay it on T1 image?
Looking forward to your reply.
Thanks again.

Best regards,
Ziqian Wang

**Comment by dorianps** [comment]
You can save all the outputs automatically by adding the `saveDir` argument. Example:
```
lsm = lesymap(... , saveDir='/path/to/save/folder')
```

Internally, this calls `save.lesymap()`, which you can also call a posteriori with something like `save.lesymap(lsm)`, where `lsm` is the output produced by the `lesymap()` function. If you specify the template, you will also get bitmaps of the overlays, while the various maps are saved as `.nii.gz` .
