### ISSUE TITLE
Info.txt File is Empty

### ISSUE THREAD

**Issue by mbowren** [dorianps/LESYMAP#12]
Hi Dr. Pustina,

A minor issue that my colleagues and I have run into is that when the new version of LESYMAP produces Info.txt files that are empty. The procedure runs properly and produces stat_img.nii.gz files correctly. However, as it finishes and saves the analysis it says that a script was out of bounds for Info.txt.

Thank you!

Mark Bowren

**Comment by dorianps** [comment]
Hi Mark,

What do you see on the screen exactly? The save function simply parses the returned lsm object to save a few things, so there is some sort of unusual output that I haven't thought about. Can you try to find what sub-variable is causing the issue, and then do something like `str(lsm$problemvariable)`? In alternative you can save the full lsm object with `save.ANTsR('lsmobject', '/path/to/saveto')` and send me the full saved folder.

Dorian

**Comment by mbowren** [comment]
Here is the message:

Error in callinfo[[16]] : subscript out of bounds

I tried to follow your instructions (to use str and save.ANTsR) but it seems like the object was not even saved in the R environment to begin with:

> lsm.Gv.bi
Error: object 'lsm.Gv.bi' not found

Mark

**Comment by mbowren** [comment]
Here is an example of the full script with errors:

> lsm.Gv.bi = lesymap(filenames, behavior, method = 'sccan', minSubjectPerVoxel = "3", saveDir = "/Users/mbowren/Documents/uiowa/core/lsm/lesymap/running/jb3_bi/Gv/sccan/overlap_3")
11:53:56 Running LESYMAP 0.0.0.9201 
11:53:56 Checking a few things...
11:53:56 Loading behavioral data...450 scores found.
11:54:07 Filenames as input, checking lesion values on 1st image...
11:54:07 SCCAN method: ignoring patch, nperm, and multiple comparison...
11:54:07 Searching voxels lesioned >= 3 subjects...486486 found
11:55:42 noPatch true - Patches will not be used...
11:55:43 Computing lesion matrix... 450x486486
11:56:37 Running analysis: sccan ...
       Searching for optimal sparseness:
         lower/upper bound:	  -0.9 / 0.9
         cvRepetitions:		  3
         nFolds:		  4
         sparsenessPenalty:	  0.03
         optim tolerance:	  0.03
11:57:17        Checking sparseness -0.212 ... CV correlation 0.329 (0.435) (cost=0.677)
14:33:28        Checking sparseness 0.212 ... CV correlation 0.287 (0.342) (cost=0.719)
16:47:34        Checking sparseness -0.475 ... CV correlation 0.325 (0.418) (cost=0.689)
19:23:55        Checking sparseness -0.236 ... CV correlation 0.327 (0.434) (cost=0.680)
22:02:36        Checking sparseness -0.05 ... CV correlation 0.327 (0.429) (cost=0.675)
00:41:11        Checking sparseness -0.12 ... CV correlation 0.330 (0.437) (cost=0.674)
03:18:21        Checking sparseness -0.105 ... CV correlation 0.329 (0.437) (cost=0.674)
05:57:23        Checking sparseness -0.156 ... CV correlation 0.329 (0.437) (cost=0.676)
08:36:29        Checking sparseness -0.134 ... CV correlation 0.330 (0.437) (cost=0.674)
11:15:23        Checking sparseness -0.12 ... CV correlation 0.330 (0.437) (cost=0.674)
       Found optimal sparsenes -0.12 (CV corr=0.33 p=7.28e-13)
       Calling SCCAN with:
            Components = 1
            Use ranks = 1
            Sparseness = -0.12
            Cluster threshold = 150
            Smooth sigma = 0.4
            Iterations = 20
            maxBased = FALSE
            directionalSCCAN = TRUE
            Permutations = 0
14:14:38 Preparing images...
14:14:38 Logging call details...
14:14:38 Saving on disk...
Error in callinfo[[16]] : subscript out of bounds
In addition: Warning message:
In lsm_sccan(lesmat, behavior, mask = mask, showInfo = showInfo,  : 
       Cluster thresholding removed all voxels.

**Comment by dorianps** [comment]
Looks like I bug i created somehow. Fixed it with https://github.com/dorianps/LESYMAP/commit/93750e1fc35abfebc8f4fb07a51dcaee69cd7455

Resintall LESYMAP, make sure the new version is 0.0.0.9202 with `packageVersion('LESYMAP')`, and let me know if you the error is gone.

Dorian

**Comment by dorianps** [comment]
Private report indicate the bug is fixed by above commits. Closing.
