### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by avrvaidya** [dorianps/LESYMAP#2]
Hi! 

Thanks for putting this package on Github! I am very excited to give it a try... 

I have tried to install the package via the four suggested methods, but have run into the same error each time:

The error I get looks something like this:

> ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [LESYMAP.so] Error 1
> ERROR: compilation failed for package ‘LESYMAP’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/LESYMAP’
> Installation failed: Command failed (1)

I am trying to do this installation via RStudio on a Mac running OS 10.12.6.

Thanks in advance!
Avi

**Comment by dorianps** [comment]
Hi Avi,

Were you able to install ANTsR, does ANTsR work?

If not, that is the first step.
If yes, there might be some problem with BLAS libraries that I have put in
Makevars
https://github.com/dorianps/LESYMAP/blob/master/src/Makevars
PKG_LIBS= `$(R_HOME)/bin/Rscript -e "Rcpp::LdFlags()"` $(LAPACK_LIBS)
$(BLAS_LIBS) $(FLIBS)

I am not sure how these libraries are used but they seemed to be required
for Rcpp to compile functions correctly. You can try downloading Lesymap in
a local folder, delete the Makevars file inside the "src" folder, then run
R CMD INSTALL LESYMAP from the command line, where LESYMAP is the folder
you placed all files.

Note, the package is tested automatically on a Mac environment. It passed
all tests earlier, I started another test to see if it works:
https://travis-ci.org/dorianps/LESYMAP/jobs/244766486

Dorian

**Comment by dorianps** [comment]
Avi, looks like this problem is known in Mac.

Ignore my response above and try the solutions explained here first:
http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

**Comment by avrvaidya** [comment]
Hi Dorian,

Thanks a lot for the very fast replies! Your second solution worked. For
the record, ANTsR was installed correctly before, so there was no problem
there.

Best,
Avi
