### ISSUE TITLE
Hang my laptop during installation

### ISSUE THREAD

**Issue by gunjan2210** [dorianps/LESYMAP#22]
Hi sir,
My laptop hang when I was installing lesymap. Is this because I am using a laptop of low ram?
 
Thanks and regards 
Gunjan

**Comment by dorianps** [comment]
I have not seen this before. The installation includes antsr, antsrcore,
and itkr, which also require the installation of other packages. Many of
these require compiling, which takes time and CPU. You can look at the
command line if the installation is proceeding. Fyi, on a recent laptop the
installation may take even 2 hours, and 1 hour on a desktop. Maybe give it
some time before proceeding. The ram in my opinion is needed later when you
analyze data, not much when you install the software.

**Comment by gunjan2210** [comment]
The itkr package is installed but after that during antsrcore installation, the pc hanged and the command line is also not proceeding.
![IMG_20200517_230036](https://user-images.githubusercontent.com/65503397/82155392-43e5c400-9892-11ea-880c-9b7c07b982da.jpg)

**Comment by dorianps** [comment]
Maybe give it another try if it doesn't proceed in a couple of hours. Then
open an issue on the antsr GitHub. One way to circumvent the problem is to
install binaries for those three packages, check the antsr GitHub for how
to do that. How old/small is your computer anyway?

**Comment by dorianps** [comment]
Btw, there are docker containers ready to go. Check
GitHub.com/dorianps/docker

**Comment by gunjan2210** [comment]
My computer is 4 years old. 
Okay I will try to do what you suggest.
Thanks for your response

**Comment by dorianps** [comment]
Is this resolved now? Please close the issue if so (maybe explain how you made it work to help others that will have your same problem).

**Comment by gunjan2210** [comment]
Hi,
Sorry for late response. I installed docker containers and that resolved my problem.

Thanks and regards
Gunjan
