### ISSUE TITLE
checkmask

### ISSUE THREAD

**Issue by BvdV-droid** [dorianps/LESYMAP#29]
Dear Dorian, 

I am kind of a newbie when it comes to lesion registration. registerLesionToTemplate throws the error in checkMask(subImg, subLesion) :   Mismatch directions of mask and 4D input. antsGetDirection indeed shows a (very slight) mismatch between the directions of the lesion and the, in this case T1 image. I am in the dark as to why this would occur (as I followed your really clear youtube instruction video) Is there anything I could do about this? 

              antsGetDirection('anat_t1.nii.gz')
[,1]         [,2]       [,3]
[1,] -0.999606716 -0.003673195 0.02780145
[2,]  0.004524308 -0.999521065 0.03061325
[3,]  0.027675688  0.030726996 0.99914459
> antsGetDirection('lesion_left_new.nii.gz')
             [,1]         [,2]       [,3]
[1,] -0.999606716 -0.003673195 0.02780145
[2,]  0.004524308 -0.999521065 0.03061325
[3,]  0.027675687  0.030726993 0.99914459

Thanx! 

Tim

**Comment by dorianps** [comment]
If you are sure the mask is in the same space as the MRI scan, you can use `antsCopyImageInfo()` to copy the headers of the scan on the mask, as seen in this thread:
https://github.com/ANTsX/ANTsR/issues/301

You can also set just the orientation with `antsSetDirection()`.

However, before doing that, I would load the T1 and the mask on ITKsnap. If snap accepts the mask as a segmentation to overlay on the scan, you should be safe to copy the header from one to the other.

**Comment by BvdV-droid** [comment]
Thank you very much for the quick response!

Op do 6 mei 2021 om 16:16 schreef dorianps ***@***.***>:
