### ISSUE TITLE
Call precision，accuracy，f1 score and recall

### ISSUE THREAD

**Issue by yangwei1993** [dorianps/LESYMAP#32]
Hi，I am using sccan to predict a binary behaviour data. I don't know how to recall back the model's predicting accuracy, precision,f1 score and recall. Could you help me?

**Comment by dorianps** [comment]
The predict function just produces scores for out of sample data. It is not
designed to go further and compare with ground truth. By the way, I think
sccan is going to produce continuous scores, not groups. The scores you ask
about are used when the output is binary and you are trying to classify new
subjects in two groups.

Nonetheless, it is very easy in R to compute those scores if you have the
two vectors of true and predicted groups. You can Google those terms to
learn more.
